# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.CreateIndexResponse do
  @moduledoc """
  Returns index creation status
  """

  @derive Jason.Encoder
  defstruct [
    :created,
    :existed
  ]

  @type t :: %__MODULE__{
    :created => boolean(),
    :existed => boolean()
  }

  def decode(value) do
    value
  end
end

