# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.DecodeGeohashResponse do
  @moduledoc """
  Returns geohash decoded as latitude/longitude with precision errors
  """

  @derive Jason.Encoder
  defstruct [
    :lat,
    :lat_error,
    :lng,
    :lng_error
  ]

  @type t :: %__MODULE__{
    :lat => float(),
    :lat_error => float(),
    :lng => float(),
    :lng_error => float()
  }

  def decode(value) do
    value
  end
end

