# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.InsertKey do
  @moduledoc """
  Arguments for inserting a key
  """

  @derive Jason.Encoder
  defstruct [
    :key,
    :lat,
    :lng,
    :ttl
  ]

  @type t :: %__MODULE__{
    :key => String.t,
    :lat => float(),
    :lng => float(),
    :ttl => integer() | nil
  }

  def decode(value) do
    value
  end
end

