# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.InsertKeyBatch do
  @moduledoc """
  Arguments for inserting multiple keys
  """

  @derive Jason.Encoder
  defstruct [
    :keys,
    :preserve_order
  ]

  @type t :: %__MODULE__{
    :keys => [GeoproxServer.Model.InsertKey.t],
    :preserve_order => boolean()
  }

  alias GeoproxServer.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:keys, :list, GeoproxServer.Model.InsertKey)
  end
end

