# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.QueryRangeResponse do
  @moduledoc """
  Returns object keys found with their distance
  """

  @derive Jason.Encoder
  defstruct [
    :found
  ]

  @type t :: %__MODULE__{
    :found => [GeoproxServer.Model.Neighbor.t]
  }

  alias GeoproxServer.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:found, :list, GeoproxServer.Model.Neighbor)
  end
end

