# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.QueryRangeMany do
  @moduledoc """
  Arguments for group range query
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :indices,
    :lat,
    :lng,
    :range,
    :sorted
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :indices => [String.t],
    :lat => float(),
    :lng => float(),
    :range => integer(),
    :sorted => boolean() | nil
  }

  def decode(value) do
    value
  end
end

