# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.RemoveKey do
  @moduledoc """
  Arguments for removing a key
  """

  @derive Jason.Encoder
  defstruct [
    :key
  ]

  @type t :: %__MODULE__{
    :key => String.t
  }

  def decode(value) do
    value
  end
end

