# NOTE: This file is auto generated by OpenAPI Generator 7.7.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule GeoproxServer.Model.RemoveKeyResponse do
  @moduledoc """
  Returns key and deletion status
  """

  @derive Jason.Encoder
  defstruct [
    :deleted,
    :key
  ]

  @type t :: %__MODULE__{
    :deleted => boolean(),
    :key => String.t
  }

  def decode(value) do
    value
  end
end

