/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.1
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeoproxClient.Client.OpenAPIDateConverter;

namespace GeoproxClient.Model
{
    /// <summary>
    /// Arguments for inserting multiple keys
    /// </summary>
    [DataContract(Name = "InsertKeyBatch")]
    public partial class InsertKeyBatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertKeyBatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InsertKeyBatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertKeyBatch" /> class.
        /// </summary>
        /// <param name="keys">Object key (required).</param>
        /// <param name="preserveOrder">preserveOrder (required).</param>
        public InsertKeyBatch(List<InsertKey> keys = default(List<InsertKey>), bool preserveOrder = default(bool))
        {
            // to ensure "keys" is required (not null)
            if (keys == null)
            {
                throw new ArgumentNullException("keys is a required property for InsertKeyBatch and cannot be null");
            }
            this.Keys = keys;
            this.PreserveOrder = preserveOrder;
        }

        /// <summary>
        /// Object key
        /// </summary>
        /// <value>Object key</value>
        [DataMember(Name = "keys", IsRequired = true, EmitDefaultValue = true)]
        public List<InsertKey> Keys { get; set; }

        /// <summary>
        /// Gets or Sets PreserveOrder
        /// </summary>
        [DataMember(Name = "preserve_order", IsRequired = true, EmitDefaultValue = true)]
        public bool PreserveOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsertKeyBatch {\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  PreserveOrder: ").Append(PreserveOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
