/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeoproxClient.Client.OpenAPIDateConverter;

namespace GeoproxClient.Model
{
    /// <summary>
    /// Returns object keys found with their distance
    /// </summary>
    [DataContract(Name = "QueryRangeResponse")]
    public partial class QueryRangeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryRangeResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueryRangeResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryRangeResponse" /> class.
        /// </summary>
        /// <param name="found">Object keys found within range (required).</param>
        public QueryRangeResponse(List<Neighbor> found = default(List<Neighbor>))
        {
            // to ensure "found" is required (not null)
            if (found == null)
            {
                throw new ArgumentNullException("found is a required property for QueryRangeResponse and cannot be null");
            }
            this.Found = found;
        }

        /// <summary>
        /// Object keys found within range
        /// </summary>
        /// <value>Object keys found within range</value>
        [DataMember(Name = "found", IsRequired = true, EmitDefaultValue = true)]
        public List<Neighbor> Found { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryRangeResponse {\n");
            sb.Append("  Found: ").Append(Found).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
