# coding: utf-8

"""
    geoprox-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoprox_client.models.geohash_neighbors_response import GeohashNeighborsResponse

class TestGeohashNeighborsResponse(unittest.TestCase):
    """GeohashNeighborsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeohashNeighborsResponse:
        """Test GeohashNeighborsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeohashNeighborsResponse`
        """
        model = GeohashNeighborsResponse()
        if include_optional:
            return GeohashNeighborsResponse(
                e = '',
                n = '',
                ne = '',
                nw = '',
                s = '',
                se = '',
                sw = '',
                w = ''
            )
        else:
            return GeohashNeighborsResponse(
                e = '',
                n = '',
                ne = '',
                nw = '',
                s = '',
                se = '',
                sw = '',
                w = '',
        )
        """

    def testGeohashNeighborsResponse(self):
        """Test GeohashNeighborsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
