# coding: utf-8

"""
    geoprox-server

    Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

    The version of the OpenAPI document: 0.4.0
    Contact: singhezra@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoprox_client.models.insert_key_batch import InsertKeyBatch

class TestInsertKeyBatch(unittest.TestCase):
    """InsertKeyBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsertKeyBatch:
        """Test InsertKeyBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsertKeyBatch`
        """
        model = InsertKeyBatch()
        if include_optional:
            return InsertKeyBatch(
                keys = [
                    geoprox_client.models.insert_key.InsertKey(
                        key = '', 
                        lat = 1.337, 
                        lng = 1.337, )
                    ],
                preserve_order = True
            )
        else:
            return InsertKeyBatch(
                keys = [
                    geoprox_client.models.insert_key.InsertKey(
                        key = '', 
                        lat = 1.337, 
                        lng = 1.337, )
                    ],
                preserve_order = True,
        )
        """

    def testInsertKeyBatch(self):
        """Test InsertKeyBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
