# coding: utf-8

"""
    geoprox-server

    Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

    The version of the OpenAPI document: 0.4.0
    Contact: singhezra@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoprox_client.models.remove_key_batch import RemoveKeyBatch

class TestRemoveKeyBatch(unittest.TestCase):
    """RemoveKeyBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveKeyBatch:
        """Test RemoveKeyBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveKeyBatch`
        """
        model = RemoveKeyBatch()
        if include_optional:
            return RemoveKeyBatch(
                keys = [
                    ''
                    ]
            )
        else:
            return RemoveKeyBatch(
                keys = [
                    ''
                    ],
        )
        """

    def testRemoveKeyBatch(self):
        """Test RemoveKeyBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
