# coding: utf-8

"""
    geoprox-server

    Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

    The version of the OpenAPI document: 0.4.0
    Contact: singhezra@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from geoprox_client.models.insert_key_batch_response import InsertKeyBatchResponse

class TestInsertKeyBatchResponse(unittest.TestCase):
    """InsertKeyBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsertKeyBatchResponse:
        """Test InsertKeyBatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsertKeyBatchResponse`
        """
        model = InsertKeyBatchResponse()
        if include_optional:
            return InsertKeyBatchResponse(
                errors = {
                    'key' : ''
                    },
                results = {
                    'key' : ''
                    }
            )
        else:
            return InsertKeyBatchResponse(
                errors = {
                    'key' : ''
                    },
                results = {
                    'key' : ''
                    },
        )
        """

    def testInsertKeyBatchResponse(self):
        """Test InsertKeyBatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
