=begin
#geoprox-server

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeoproxClient::GeoshardApiApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GeoshardApiApi' do
  before do
    # run before each test
    @api_instance = GeoproxClient::GeoshardApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GeoshardApiApi' do
    it 'should create an instance of GeoshardApiApi' do
      expect(@api_instance).to be_instance_of(GeoproxClient::GeoshardApiApi)
    end
  end

  # unit tests for create_index
  # Create geospatial index
  # Creates an in-memory index within this geoshard
  # @param index 
  # @param [Hash] opts the optional parameters
  # @return [CreateIndexResponse]
  describe 'create_index test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for drop_index
  # Drop index
  # Deletes geospatial index, all keys will be lost
  # @param index 
  # @param [Hash] opts the optional parameters
  # @return [DropIndexResponse]
  describe 'drop_index test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for insert_key
  # Insert key into index
  # Inserts key into geospatial index
  # @param index 
  # @param insert_key 
  # @param [Hash] opts the optional parameters
  # @return [InsertKeyResponse]
  describe 'insert_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for query_range
  # Search nearby
  # Search geospatial index for all keys within some distance
  # @param lat latitude
  # @param lng longitude
  # @param range search radius in kilometers
  # @param index 
  # @param [Hash] opts the optional parameters
  # @return [QueryRangeResponse]
  describe 'query_range test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_key
  # Remove key from index
  # Removed key from geospatial index
  # @param index 
  # @param remove_key 
  # @param [Hash] opts the optional parameters
  # @return [InsertKeyResponse]
  describe 'remove_key test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
