/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Arguments for encoding latitude/longitude as geohash
 *
 * @param depth Determines geohash length
 * @param lat Latitude
 * @param lng Longitude
 */


data class EncodeLatLng (

    /* Determines geohash length */
    @Json(name = "depth")
    val depth: kotlin.Int,

    /* Latitude */
    @Json(name = "lat")
    val lat: kotlin.Double,

    /* Longitude */
    @Json(name = "lng")
    val lng: kotlin.Double

) {


}

