/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returns geohash encoded latitude/longitude
 *
 * @param geohash 
 */


data class EncodeLatLngResponse (

    @Json(name = "geohash")
    val geohash: kotlin.String

) {


}

