/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Neighboring geohash regions
 *
 * @param e East
 * @param n North
 * @param ne North East
 * @param nw North West
 * @param s South
 * @param se South East
 * @param sw South West
 * @param w West
 */


data class GeohashNeighborsResponse (

    /* East */
    @Json(name = "e")
    val e: kotlin.String,

    /* North */
    @Json(name = "n")
    val n: kotlin.String,

    /* North East */
    @Json(name = "ne")
    val ne: kotlin.String,

    /* North West */
    @Json(name = "nw")
    val nw: kotlin.String,

    /* South */
    @Json(name = "s")
    val s: kotlin.String,

    /* South East */
    @Json(name = "se")
    val se: kotlin.String,

    /* South West */
    @Json(name = "sw")
    val sw: kotlin.String,

    /* West */
    @Json(name = "w")
    val w: kotlin.String

) {


}

