/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returns results and errors of batch key insert
 *
 * @param errors Contains information about which keys failed to be inserted and the associated error details.
 * @param results Object keys that have been inserted in the index and their geohash.
 */


data class InsertKeyBatchResponse (

    /* Contains information about which keys failed to be inserted and the associated error details. */
    @Json(name = "errors")
    val errors: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* Object keys that have been inserted in the index and their geohash. */
    @Json(name = "results")
    val results: kotlin.collections.Map<kotlin.String, kotlin.String>

) {


}

