/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Arguments for inserting a key
 *
 * @param key Object key
 * @param lat Latitude
 * @param lng Longitude
 * @param ttl The time-to-live (TTL) for this key, in seconds
 */


data class InsertKey (

    /* Object key */
    @Json(name = "key")
    val key: kotlin.String,

    /* Latitude */
    @Json(name = "lat")
    val lat: kotlin.Double,

    /* Longitude */
    @Json(name = "lng")
    val lng: kotlin.Double,

    /* The time-to-live (TTL) for this key, in seconds */
    @Json(name = "ttl")
    val ttl: kotlin.Long? = null

) {


}

