/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models

import org.geoprox.client.models.InsertKey

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Arguments for inserting multiple keys
 *
 * @param propertyKeys Object key
 * @param preserveOrder 
 * @param ttl The time-to-live (TTL) for these keys, in seconds
 */


data class InsertKeyBatch (

    /* Object key */
    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<InsertKey>,

    @Json(name = "preserve_order")
    val preserveOrder: kotlin.Boolean,

    /* The time-to-live (TTL) for these keys, in seconds */
    @Json(name = "ttl")
    val ttl: kotlin.Long? = null

) {


}

