# coding: utf-8

"""
    geoprox-server

    Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

    The version of the OpenAPI document: 0.2.0
    Contact: singhezra@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "geoprox-client"
VERSION = "0.3.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="geoprox-server",
    author="Ezra Singh",
    author_email="singhezra@gmail.com",
    url="https://github.com/ezrasingh/geoprox/contrib/client-sdk/python/",
    keywords=["OpenAPI", "OpenAPI-Generator", "geoprox-server"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT OR Apache-2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
    """,  # noqa: E501
    package_data={"geoprox_client": ["py.typed"]},
)
