services:
  geoprox:
    build:
      dockerfile: contrib/docker/Dockerfile.alpine
      context: ../../../

    command: -c geoprox.toml

    ports:
      - 5000:5000
    volumes:
      - ./geoprox.toml:/var/lib/geoprox/geoprox.toml:ro
      - snapshots:/var/lib/geoprox/snapshots

volumes:
  snapshots:
