services:
  geoprox:
    build:
      dockerfile: contrib/docker/Dockerfile.alpine
      context: ../../../

    environment:
      GEOPROX_CONFIG: /var/lib/geoprox/geoprox.toml
      GEOPROX_HTTP_ADDR: 0.0.0.0
      GEOPROX_HTTP_PORT: 5000

    ports:
      - 5000:5000
    volumes:
      - ./geoprox.toml:/var/lib/geoprox/geoprox.toml:ro
      - snapshots:/var/lib/geoprox/snapshots

volumes:
  snapshots:
