/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.geoprox.client.models.DecodeGeohashResponse

class DecodeGeohashResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DecodeGeohashResponse
        //val modelInstance = DecodeGeohashResponse()

        // to test the property `lat` - Latitude
        should("test lat") {
            // uncomment below to test the property
            //modelInstance.lat shouldBe ("TODO")
        }

        // to test the property `latError` - Latitude error
        should("test latError") {
            // uncomment below to test the property
            //modelInstance.latError shouldBe ("TODO")
        }

        // to test the property `lng` - Longitude
        should("test lng") {
            // uncomment below to test the property
            //modelInstance.lng shouldBe ("TODO")
        }

        // to test the property `lngError` - Longitude error
        should("test lngError") {
            // uncomment below to test the property
            //modelInstance.lngError shouldBe ("TODO")
        }

    }
}
