/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.geoprox.client.models.EncodeLatLngResponse

class EncodeLatLngResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EncodeLatLngResponse
        //val modelInstance = EncodeLatLngResponse()

        // to test the property `geohash`
        should("test geohash") {
            // uncomment below to test the property
            //modelInstance.geohash shouldBe ("TODO")
        }

    }
}
