/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.geoprox.client.models.QueryRangeResponse
import org.geoprox.client.models.Neighbor

class QueryRangeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryRangeResponse
        //val modelInstance = QueryRangeResponse()

        // to test the property `found` - Object keys found within range
        should("test found") {
            // uncomment below to test the property
            //modelInstance.found shouldBe ("TODO")
        }

    }
}
