/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.geoprox.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.geoprox.client.models.RemoveKeyBatch

class RemoveKeyBatchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RemoveKeyBatch
        //val modelInstance = RemoveKeyBatch()

        // to test the property `propertyKeys` - Object key
        should("test propertyKeys") {
            // uncomment below to test the property
            //modelInstance.propertyKeys shouldBe ("TODO")
        }

    }
}
