/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Returns index creation status
*/
export class CreateIndexResponse {
    /**
    * If true index was created
    */
    'created': boolean;
    /**
    * If true index alredy exist
    */
    'existed': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "boolean"
        },
        {
            "name": "existed",
            "baseName": "existed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CreateIndexResponse.attributeTypeMap;
    }
}

