/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.2
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Returns geohash encoded latitude/longitude
*/
export class EncodeLatLngResponse {
    'geohash': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "geohash",
            "baseName": "geohash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EncodeLatLngResponse.attributeTypeMap;
    }
}

