/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Arguments for range query
*/
export class QueryRange {
    /**
    * Latitude
    */
    'lat': number;
    /**
    * Longitude
    */
    'lng': number;
    /**
    * Search radius in kilometers
    */
    'range': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lat",
            "baseName": "lat",
            "type": "number"
        },
        {
            "name": "lng",
            "baseName": "lng",
            "type": "number"
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return QueryRange.attributeTypeMap;
    }
}

