=begin
#geoprox-server

#Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

The version of the OpenAPI document: 0.4.0
Contact: singhezra@gmail.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GeoproxClient::InsertKeyBatchResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe GeoproxClient::InsertKeyBatchResponse do
  let(:instance) { GeoproxClient::InsertKeyBatchResponse.new }

  describe 'test an instance of InsertKeyBatchResponse' do
    it 'should create an instance of InsertKeyBatchResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(GeoproxClient::InsertKeyBatchResponse)
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
