/*
geoprox-server

Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

API version: 0.4.2
Contact: singhezra@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoprox_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InsertKeyBatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsertKeyBatch{}

// InsertKeyBatch Arguments for inserting multiple keys
type InsertKeyBatch struct {
	// Object key
	Keys []InsertKey `json:"keys"`
	PreserveOrder bool `json:"preserve_order"`
}

type _InsertKeyBatch InsertKeyBatch

// NewInsertKeyBatch instantiates a new InsertKeyBatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsertKeyBatch(keys []InsertKey, preserveOrder bool) *InsertKeyBatch {
	this := InsertKeyBatch{}
	this.Keys = keys
	this.PreserveOrder = preserveOrder
	return &this
}

// NewInsertKeyBatchWithDefaults instantiates a new InsertKeyBatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsertKeyBatchWithDefaults() *InsertKeyBatch {
	this := InsertKeyBatch{}
	return &this
}

// GetKeys returns the Keys field value
func (o *InsertKeyBatch) GetKeys() []InsertKey {
	if o == nil {
		var ret []InsertKey
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *InsertKeyBatch) GetKeysOk() ([]InsertKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *InsertKeyBatch) SetKeys(v []InsertKey) {
	o.Keys = v
}

// GetPreserveOrder returns the PreserveOrder field value
func (o *InsertKeyBatch) GetPreserveOrder() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PreserveOrder
}

// GetPreserveOrderOk returns a tuple with the PreserveOrder field value
// and a boolean to check if the value has been set.
func (o *InsertKeyBatch) GetPreserveOrderOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreserveOrder, true
}

// SetPreserveOrder sets field value
func (o *InsertKeyBatch) SetPreserveOrder(v bool) {
	o.PreserveOrder = v
}

func (o InsertKeyBatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsertKeyBatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	toSerialize["preserve_order"] = o.PreserveOrder
	return toSerialize, nil
}

func (o *InsertKeyBatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
		"preserve_order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsertKeyBatch := _InsertKeyBatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInsertKeyBatch)

	if err != nil {
		return err
	}

	*o = InsertKeyBatch(varInsertKeyBatch)

	return err
}

type NullableInsertKeyBatch struct {
	value *InsertKeyBatch
	isSet bool
}

func (v NullableInsertKeyBatch) Get() *InsertKeyBatch {
	return v.value
}

func (v *NullableInsertKeyBatch) Set(val *InsertKeyBatch) {
	v.value = val
	v.isSet = true
}

func (v NullableInsertKeyBatch) IsSet() bool {
	return v.isSet
}

func (v *NullableInsertKeyBatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsertKeyBatch(val *InsertKeyBatch) *NullableInsertKeyBatch {
	return &NullableInsertKeyBatch{value: val, isSet: true}
}

func (v NullableInsertKeyBatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsertKeyBatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


