/*
geoprox-server

Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

API version: 0.5.0
Contact: singhezra@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package geoprox_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveKey{}

// RemoveKey Arguments for removing a key
type RemoveKey struct {
	// Object key
	Key string `json:"key"`
}

type _RemoveKey RemoveKey

// NewRemoveKey instantiates a new RemoveKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveKey(key string) *RemoveKey {
	this := RemoveKey{}
	this.Key = key
	return &this
}

// NewRemoveKeyWithDefaults instantiates a new RemoveKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveKeyWithDefaults() *RemoveKey {
	this := RemoveKey{}
	return &this
}

// GetKey returns the Key field value
func (o *RemoveKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *RemoveKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *RemoveKey) SetKey(v string) {
	o.Key = v
}

func (o RemoveKey) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *RemoveKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveKey := _RemoveKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveKey)

	if err != nil {
		return err
	}

	*o = RemoveKey(varRemoveKey)

	return err
}

type NullableRemoveKey struct {
	value *RemoveKey
	isSet bool
}

func (v NullableRemoveKey) Get() *RemoveKey {
	return v.value
}

func (v *NullableRemoveKey) Set(val *RemoveKey) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveKey) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveKey(val *RemoveKey) *NullableRemoveKey {
	return &NullableRemoveKey{value: val, isSet: true}
}

func (v NullableRemoveKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


