=begin
#geoprox-server

#Geoprox server implementation providing a HTTP API for geospatial queries and position tracking

The version of the OpenAPI document: 0.5.0
Contact: singhezra@gmail.com
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

# Common files
require 'geoprox_client/api_client'
require 'geoprox_client/api_error'
require 'geoprox_client/version'
require 'geoprox_client/configuration'

# Models
require 'geoprox_client/models/create_index_response'
require 'geoprox_client/models/decode_geohash_response'
require 'geoprox_client/models/drop_index_response'
require 'geoprox_client/models/encode_lat_lng'
require 'geoprox_client/models/encode_lat_lng_response'
require 'geoprox_client/models/geohash_neighbors_response'
require 'geoprox_client/models/insert_key'
require 'geoprox_client/models/insert_key_batch'
require 'geoprox_client/models/insert_key_batch_response'
require 'geoprox_client/models/insert_key_response'
require 'geoprox_client/models/neighbor'
require 'geoprox_client/models/query_range'
require 'geoprox_client/models/query_range_many'
require 'geoprox_client/models/query_range_many_response'
require 'geoprox_client/models/query_range_response'
require 'geoprox_client/models/remove_key'
require 'geoprox_client/models/remove_key_batch'
require 'geoprox_client/models/remove_key_batch_response'
require 'geoprox_client/models/remove_key_response'

# APIs
require 'geoprox_client/api/geohash_api_api'
require 'geoprox_client/api/geoshard_api_api'

module GeoproxClient
  class << self
    # Customize default settings for the SDK using block.
    #   GeoproxClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
