// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Returns index creation status
 * @export
 * @interface CreateIndexResponse
 */
export interface CreateIndexResponse {
    /**
     * If true index was created
     * @type {boolean}
     * @memberof CreateIndexResponse
     */
    created: boolean;
    /**
     * If true index alredy exist
     * @type {boolean}
     * @memberof CreateIndexResponse
     */
    existed: boolean;
}
