// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Returns index deletion status
 * @export
 * @interface DropIndexResponse
 */
export interface DropIndexResponse {
    /**
     * If true index was deleted
     * @type {boolean}
     * @memberof DropIndexResponse
     */
    deleted: boolean;
}
