// tslint:disable
/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Neighboring geohash regions
 * @export
 * @interface GeohashNeighborsResponse
 */
export interface GeohashNeighborsResponse {
    /**
     * East
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    e: string;
    /**
     * North
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    n: string;
    /**
     * North East
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    ne: string;
    /**
     * North West
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    nw: string;
    /**
     * South
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    s: string;
    /**
     * South East
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    se: string;
    /**
     * South West
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    sw: string;
    /**
     * West
     * @type {string}
     * @memberof GeohashNeighborsResponse
     */
    w: string;
}
