// tslint:disable
/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Arguments for inserting a key
 * @export
 * @interface InsertKey
 */
export interface InsertKey {
    /**
     * resource key
     * @type {string}
     * @memberof InsertKey
     */
    key: string;
    /**
     * latitude
     * @type {number}
     * @memberof InsertKey
     */
    lat: number;
    /**
     * longitude
     * @type {number}
     * @memberof InsertKey
     */
    lng: number;
}
