// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.2
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Arguments for inserting a key
 * @export
 * @interface InsertKey
 */
export interface InsertKey {
    /**
     * Object key
     * @type {string}
     * @memberof InsertKey
     */
    key: string;
    /**
     * Latitude
     * @type {number}
     * @memberof InsertKey
     */
    lat: number;
    /**
     * Longitude
     * @type {number}
     * @memberof InsertKey
     */
    lng: number;
}
