// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    InsertKey,
} from './';

/**
 * Arguments for inserting multiple keys
 * @export
 * @interface InsertKeyBatch
 */
export interface InsertKeyBatch {
    /**
     * Object key
     * @type {Array<InsertKey>}
     * @memberof InsertKeyBatch
     */
    keys: Array<InsertKey>;
    /**
     * @type {boolean}
     * @memberof InsertKeyBatch
     */
    preserve_order: boolean;
}
