// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Neighbor,
} from './';

/**
 * Returns resource keys found with their distance
 * @export
 * @interface QueryRangeResponse
 */
export interface QueryRangeResponse {
    /**
     * Resource keys found within range
     * @type {Array<Neighbor>}
     * @memberof QueryRangeResponse
     */
    found: Array<Neighbor>;
}
