// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Arguments for group range query
 * @export
 * @interface QueryRangeMany
 */
export interface QueryRangeMany {
    /**
     * Maximum number of neighbors that can be returned (default 100)
     * @type {number}
     * @memberof QueryRangeMany
     */
    count?: number | null;
    /**
     * List of indices to search
     * @type {Array<string>}
     * @memberof QueryRangeMany
     */
    indices: Array<string>;
    /**
     * Latitude
     * @type {number}
     * @memberof QueryRangeMany
     */
    lat: number;
    /**
     * Longitude
     * @type {number}
     * @memberof QueryRangeMany
     */
    lng: number;
    /**
     * Search radius in kilometers
     * @type {number}
     * @memberof QueryRangeMany
     */
    range: number;
    /**
     * If enabled neighbors will be sorted by distance, nearest to furthest (default false)
     * @type {boolean}
     * @memberof QueryRangeMany
     */
    sorted?: boolean | null;
}
