// tslint:disable
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Arguments for removing multiple keys
 * @export
 * @interface RemoveKeyBatch
 */
export interface RemoveKeyBatch {
    /**
     * Object key
     * @type {Array<string>}
     * @memberof RemoveKeyBatch
     */
    keys: Array<string>;
}
