// tslint:disable
/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Returns key and deletion status
 * @export
 * @interface RemoveKeyResponse
 */
export interface RemoveKeyResponse {
    /**
     * If true key was removed
     * @type {boolean}
     * @memberof RemoveKeyResponse
     */
    deleted: boolean;
    /**
     * resource key
     * @type {string}
     * @memberof RemoveKeyResponse
     */
    key: string;
}
