/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeoproxClient.Model;
using GeoproxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeoproxClient.Test.Model
{
    /// <summary>
    ///  Class for testing EncodeLatLngResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EncodeLatLngResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EncodeLatLngResponse
        //private EncodeLatLngResponse instance;

        public EncodeLatLngResponseTests()
        {
            // TODO uncomment below to create an instance of EncodeLatLngResponse
            //instance = new EncodeLatLngResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EncodeLatLngResponse
        /// </summary>
        [Fact]
        public void EncodeLatLngResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EncodeLatLngResponse
            //Assert.IsType<EncodeLatLngResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Geohash'
        /// </summary>
        [Fact]
        public void GeohashTest()
        {
            // TODO unit test for the property 'Geohash'
        }
    }
}
