/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeoproxClient.Model;
using GeoproxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeoproxClient.Test.Model
{
    /// <summary>
    ///  Class for testing EncodeLatLng
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EncodeLatLngTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EncodeLatLng
        //private EncodeLatLng instance;

        public EncodeLatLngTests()
        {
            // TODO uncomment below to create an instance of EncodeLatLng
            //instance = new EncodeLatLng();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EncodeLatLng
        /// </summary>
        [Fact]
        public void EncodeLatLngInstanceTest()
        {
            // TODO uncomment below to test "IsType" EncodeLatLng
            //Assert.IsType<EncodeLatLng>(instance);
        }

        /// <summary>
        /// Test the property 'Depth'
        /// </summary>
        [Fact]
        public void DepthTest()
        {
            // TODO unit test for the property 'Depth'
        }

        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Fact]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }

        /// <summary>
        /// Test the property 'Lng'
        /// </summary>
        [Fact]
        public void LngTest()
        {
            // TODO unit test for the property 'Lng'
        }
    }
}
