/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeoproxClient.Model;
using GeoproxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeoproxClient.Test.Model
{
    /// <summary>
    ///  Class for testing Neighbor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NeighborTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Neighbor
        //private Neighbor instance;

        public NeighborTests()
        {
            // TODO uncomment below to create an instance of Neighbor
            //instance = new Neighbor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Neighbor
        /// </summary>
        [Fact]
        public void NeighborInstanceTest()
        {
            // TODO uncomment below to test "IsType" Neighbor
            //Assert.IsType<Neighbor>(instance);
        }

        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
    }
}
