/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeoproxClient.Model;
using GeoproxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeoproxClient.Test.Model
{
    /// <summary>
    ///  Class for testing RemoveKeyBatchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemoveKeyBatchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemoveKeyBatchResponse
        //private RemoveKeyBatchResponse instance;

        public RemoveKeyBatchResponseTests()
        {
            // TODO uncomment below to create an instance of RemoveKeyBatchResponse
            //instance = new RemoveKeyBatchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemoveKeyBatchResponse
        /// </summary>
        [Fact]
        public void RemoveKeyBatchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemoveKeyBatchResponse
            //Assert.IsType<RemoveKeyBatchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
    }
}
