/*
 * geoprox-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIndexResponse : Returns index creation status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIndexResponse {
    /// If true index was created
    #[serde(rename = "created")]
    pub created: bool,
    /// If true index alredy exist
    #[serde(rename = "existed")]
    pub existed: bool,
}

impl CreateIndexResponse {
    /// Returns index creation status
    pub fn new(created: bool, existed: bool) -> CreateIndexResponse {
        CreateIndexResponse {
            created,
            existed,
        }
    }
}

