/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.1
 * Contact: singhezra@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InsertKeyBatch : Arguments for inserting multiple keys
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsertKeyBatch {
    /// Object key
    #[serde(rename = "keys")]
    pub keys: Vec<models::InsertKey>,
    #[serde(rename = "preserve_order")]
    pub preserve_order: bool,
}

impl InsertKeyBatch {
    /// Arguments for inserting multiple keys
    pub fn new(keys: Vec<models::InsertKey>, preserve_order: bool) -> InsertKeyBatch {
        InsertKeyBatch {
            keys,
            preserve_order,
        }
    }
}

