/*
 * geoprox-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryRangeResponse : Returns resource keys found with their distance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRangeResponse {
    /// Resource keys found within range
    #[serde(rename = "found")]
    pub found: Vec<models::KeysFoundInner>,
}

impl QueryRangeResponse {
    /// Returns resource keys found with their distance
    pub fn new(found: Vec<models::KeysFoundInner>) -> QueryRangeResponse {
        QueryRangeResponse {
            found,
        }
    }
}

