/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.2
 * Contact: singhezra@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveKeyResponse : Returns key and deletion status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveKeyResponse {
    /// If true key was removed
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// Object key
    #[serde(rename = "key")]
    pub key: String,
}

impl RemoveKeyResponse {
    /// Returns key and deletion status
    pub fn new(deleted: bool, key: String) -> RemoveKeyResponse {
        RemoveKeyResponse {
            deleted,
            key,
        }
    }
}

