/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: singhezra@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveKey : Arguments for removing a key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveKey {
    /// Object key
    #[serde(rename = "key")]
    pub key: String,
}

impl RemoveKey {
    /// Arguments for removing a key
    pub fn new(key: String) -> RemoveKey {
        RemoveKey {
            key,
        }
    }
}

