/*
 * geoprox-server
 *
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.5.0
 * Contact: singhezra@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveKeyBatch : Arguments for removing multiple keys
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveKeyBatch {
    /// Object key
    #[serde(rename = "keys")]
    pub keys: Vec<String>,
}

impl RemoveKeyBatch {
    /// Arguments for removing multiple keys
    pub fn new(keys: Vec<String>) -> RemoveKeyBatch {
        RemoveKeyBatch {
            keys,
        }
    }
}

