/*
 * geoprox-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RemoveKeyResponse : Returns key and deletion status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveKeyResponse {
    /// If true key was removed
    #[serde(rename = "deleted")]
    pub deleted: bool,
    /// resource key
    #[serde(rename = "key")]
    pub key: String,
}

impl RemoveKeyResponse {
    /// Returns key and deletion status
    pub fn new(deleted: bool, key: String) -> RemoveKeyResponse {
        RemoveKeyResponse {
            deleted,
            key,
        }
    }
}

