[package]
name = "geoprox-server"
version = "0.1.0"
edition = "2021"

[dependencies]
geoprox-core = {path = "../geoprox-core"}
axum = { version = "0.7.5", features = ["macros"] }
serde = { version = "1.0.199", features = ["derive", "rc"] }
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
axum-test = "15.3.0"
