services:
  geoprox:
    # I recommend pinning the tag to a specific version.
    # Available tags can be found at https://hub.docker.com/repository/docker/ezrasingh/geoprox/tags
    image: ezrasingh/geoprox:${IMAGE_TAG:-latest}
    restart: on-failure:3
    command: -c geoprox.toml

    # This is optional, demonstrating how to specify env vars
    environment:
      # either use -c flag or this env var
      # GEOPROX_CONFIG: /my/custom/path/geoprox.toml
      GEOPROX_HTTP_ADDR: 0.0.0.0
      GEOPROX_HTTP_PORT: 5000

    ports:
      - ${HOST_PORT:-5000}:5000
    volumes:
      - ./geoprox.toml:/var/lib/geoprox/geoprox.toml:ro
      - ./snapshots:/var/lib/geoprox/snapshots:z

  # Here is an example to generate just the OpenAPI spec
  geoprox-spec:
    image: ezrasingh/geoprox:${IMAGE_TAG:-latest}
    entrypoint: ['geoprox', 'spec' ]
    command: --destination /tmp --filename openapi.json --pretty
    volumes:
      - ./:/tmp:z
