services:
  geoprox:
    # I recommend pinning the tag to a specific version.
    # Available tags can be found at https://hub.docker.com/repository/docker/ezrasingh/geoprox/tags
    image: ezrasingh/geoprox:latest

    # This is optional, demonstrating how to specify your config path.
    # The default path is /etc/geoprox/
    # Feel free to remove this command if you are fine with the default config path
    command: run -c /etc/geoprox/geoprox.toml

    ports:
      - 5000:5000

    volumes:
      - ./geoprox.toml:/etc/geoprox/geoprox.toml:ro
