/* tslint:disable */
/* eslint-disable */
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returns geohash encoded latitude/longitude
 * @export
 * @interface EncodeLatLngResponse
 */
export interface EncodeLatLngResponse {
    /**
     * 
     * @type {string}
     * @memberof EncodeLatLngResponse
     */
    geohash: string;
}

/**
 * Check if a given object implements the EncodeLatLngResponse interface.
 */
export function instanceOfEncodeLatLngResponse(value: object): value is EncodeLatLngResponse {
    if (!('geohash' in value) || value['geohash'] === undefined) return false;
    return true;
}

export function EncodeLatLngResponseFromJSON(json: any): EncodeLatLngResponse {
    return EncodeLatLngResponseFromJSONTyped(json, false);
}

export function EncodeLatLngResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EncodeLatLngResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'geohash': json['geohash'],
    };
}

export function EncodeLatLngResponseToJSON(value?: EncodeLatLngResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'geohash': value['geohash'],
    };
}

