/* tslint:disable */
/* eslint-disable */
/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returns key and geohash
 * @export
 * @interface InsertKeyResponse
 */
export interface InsertKeyResponse {
    /**
     * geohash encoded latitude/longitude
     * @type {string}
     * @memberof InsertKeyResponse
     */
    geohash: string;
    /**
     * resource key
     * @type {string}
     * @memberof InsertKeyResponse
     */
    key: string;
}

/**
 * Check if a given object implements the InsertKeyResponse interface.
 */
export function instanceOfInsertKeyResponse(value: object): value is InsertKeyResponse {
    if (!('geohash' in value) || value['geohash'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function InsertKeyResponseFromJSON(json: any): InsertKeyResponse {
    return InsertKeyResponseFromJSONTyped(json, false);
}

export function InsertKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'geohash': json['geohash'],
        'key': json['key'],
    };
}

export function InsertKeyResponseToJSON(value?: InsertKeyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'geohash': value['geohash'],
        'key': value['key'],
    };
}

