/* tslint:disable */
/* eslint-disable */
/**
 * geoprox-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeysFoundInner } from './KeysFoundInner';
import {
    KeysFoundInnerFromJSON,
    KeysFoundInnerFromJSONTyped,
    KeysFoundInnerToJSON,
} from './KeysFoundInner';

/**
 * Returns resource keys found with their distance
 * @export
 * @interface QueryRangeResponse
 */
export interface QueryRangeResponse {
    /**
     * Resource keys found within range
     * @type {Set<KeysFoundInner>}
     * @memberof QueryRangeResponse
     */
    found: Set<KeysFoundInner>;
}

/**
 * Check if a given object implements the QueryRangeResponse interface.
 */
export function instanceOfQueryRangeResponse(value: object): value is QueryRangeResponse {
    if (!('found' in value) || value['found'] === undefined) return false;
    return true;
}

export function QueryRangeResponseFromJSON(json: any): QueryRangeResponse {
    return QueryRangeResponseFromJSONTyped(json, false);
}

export function QueryRangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'found': (new Set((json['found'] as Array<any>).map(KeysFoundInnerFromJSON))),
    };
}

export function QueryRangeResponseToJSON(value?: QueryRangeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'found': (Array.from(value['found'] as Set<any>).map(KeysFoundInnerToJSON)),
    };
}

