/* tslint:disable */
/* eslint-disable */
/**
 * geoprox-server
 * Geoprox server implementation providing a HTTP API for geospatial queries and position tracking
 *
 * The version of the OpenAPI document: 0.3.1
 * Contact: singhezra@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returns key and deletion status
 * @export
 * @interface RemoveKeyResponse
 */
export interface RemoveKeyResponse {
    /**
     * If true key was removed
     * @type {boolean}
     * @memberof RemoveKeyResponse
     */
    deleted: boolean;
    /**
     * Resource key
     * @type {string}
     * @memberof RemoveKeyResponse
     */
    key: string;
}

/**
 * Check if a given object implements the RemoveKeyResponse interface.
 */
export function instanceOfRemoveKeyResponse(value: object): value is RemoveKeyResponse {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function RemoveKeyResponseFromJSON(json: any): RemoveKeyResponse {
    return RemoveKeyResponseFromJSONTyped(json, false);
}

export function RemoveKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
        'key': json['key'],
    };
}

export function RemoveKeyResponseToJSON(value?: RemoveKeyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'deleted': value['deleted'],
        'key': value['key'],
    };
}

