FROM rust:latest AS builder

WORKDIR /code
COPY . /code/
RUN cargo build --release

FROM debian:bookworm

RUN \
    groupadd geoprox && \
    useradd -m -g geoprox geoprox && \
    mkdir -p /var/lib/geoprox/snapshots && \
    chown geoprox:geoprox -R /var/lib/geoprox

USER geoprox:geoprox

WORKDIR /var/lib/geoprox
COPY --from=builder --chown=geoprox:geoprox /code/target/release/geoprox /usr/local/bin/

ENTRYPOINT [ "geoprox", "run" ]
