FROM rust:latest AS builder

WORKDIR /code
COPY . /code/
RUN cargo build --release

FROM alpine:3

RUN apk add libc6-compat libgcc

RUN adduser -D geoprox
USER geoprox:geoprox

WORKDIR /usr/local/bin
COPY --from=builder --chown=geoprox:geoprox /code/target/release/geoprox /usr/local/bin/
COPY --from=builder /code/geoprox/geoprox.default.toml /etc/geoprox/geoprox.toml

ENTRYPOINT [ "geoprox" ]
