FROM rust:latest AS builder

WORKDIR /code
COPY . /code/
RUN cargo build --release

FROM debian:bookworm

RUN groupadd geoprox && \
    useradd -m -g geoprox geoprox

USER geoprox:geoprox

WORKDIR /usr/local/bin
COPY --from=builder --chown=geoprox:geoprox /code/target/release/geoprox /usr/local/bin/

ENTRYPOINT [ "geoprox", "run" ]
