name: Performance Benchmarks
on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Run crate benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run benchmark
        run: cargo bench --bench spatial_index_benchmark -- --output-format bencher | tee output.txt

      - name: Store results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Geoprox Benchmark
          tool: "cargo"
          output-file-path: output.txt
          benchmark-data-dir-path: bench
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@ezrasingh"
