name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  deployments: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Generate book
        working-directory: contrib/docs
        run: mdbook build

      - name: Publish book to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./contrib/docs/book
